# Generated by Django 4.1 on 2022-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclassiffier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodels',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='weigths',
            field=models.FileField(upload_to='mlmodels/'),
        ),
    ]
